@startuml changeGrade

actor User

User -> GradeTable : change grade

alt HttpStatusCode.OK
    GradeTable -> User : return OK message
else HttpStatusCode.BadRequest
    GradeTable -> User : return NOT OK message
end

@enduml