@startuml changeSubject

actor User

User -> SubjectTable : change Subject

alt HttpStatusCode.OK
    SubjectTable -> User : return OK message
else HttpStatusCode.BadRequest
    SubjectTable -> User : return NOT OK message
end

@enduml