@startuml changeGroupSubject

actor User

User -> GroupSubject : change GroupSubject

alt HttpStatusCode.OK
    GroupSubject -> User : return OK message
else HttpStatusCode.BadRequest
    GroupSubject -> User : return NOT OK message
end

@enduml