@startuml changeGroup

actor User

User -> GroupTable : change group

alt HttpStatusCode.OK
    GroupTable -> User : return OK message
else HttpStatusCode.BadRequest
    GroupTable -> User : return NOT OK message
end

@enduml