@startuml changeStudent

actor User

User -> StudentTable : change Student

alt HttpStatusCode.OK
    StudentTable -> User : return OK message
else HttpStatusCode.BadRequest
    StudentTable -> User : return NOT OK message
end

@enduml